type <- function(x) {
  type <- "ST"
  if (str_detect(x, " PL") == T) type <- "PL"
  if (str_detect(x, " CT") == T) type <- "CT"
  if (str_detect(x, " PARK") == T) type <- "PARK"
  if (str_detect(x, " DR") == T) type <- "DR"
  if (str_detect(x, " SQ") == T) type <- "SQ"
  #if (str_detect(x, " SQUARE") == T) type <- "SQ"
  if (str_detect(x, " PLZ") == T) type <- "PLZ"
  if (str_detect(x, " CIR") == T) type <- "CIR"
  if (str_detect(x, " PKWY") == T) type <- "PKWY"
  if (str_detect(x, " WAY") == T) type <- "WAY"
  if (str_detect(x, " ALY") == T) type <- "ALY"
  if (str_detect(x, " PIER") == T) type <- "PIER"
  if (str_detect(x, "PIER ") == T) type <- "PIER"
  if (str_detect(x, " SLIP") == T) type <- "SLIP"
  if (str_detect(x, " ROW") == T) type <- "ROW"
  if (str_detect(x, " APPROACH") == T) type <- "APPROACH"
  if (str_detect(x, " LN") == T) type <- "LN"
  if (str_detect(x, " TER") == T) type <- "TER"
  if (str_detect(x, " HTS") == T) type <- "HTS"
  if (str_detect(x, " BLVD") == T) type <- "BLVD"
  if (str_detect(x, " BRG") == T) type <- "BRG"
  if (str_detect(x, " HL") == T) type <- "HL"
  if (str_detect(x, "AVE ") == T) type <- "AVE"
  if (str_detect(x, " AVE") == T) type <- "AVE"
  if (str_detect(x, "BROADWAY") == T) type <- "AVE"
  return(type)
}