---
title: "Full Dictionary"
author: "Chang Xu"
output: html_notebook
---


```{r, include=FALSE}
knitr::opts_chunk$set(error = TRUE)
knitr::opts_chunk$set(cache = F)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
options(mc.cores = parallel::detectCores())
library(zoo)
library(magrittr)
library(dplyr)
library(tidyverse)
library(openxlsx)
library(readxl)
library(stringr)
library(fuzzyjoin)
library(tm)
library(english)
library(reshape2)
library(gtools)
library(compare)
library(purrr)
```


# load data
```{r}
#morse_mn <- read_csv("Data/morse_mn1880.csv")
#morse_bk <- read_csv("Data/morse_bk1880.csv")
```
```{r}
mn_geo <- read_csv("Data/geo_dict_mn1850.csv")
bk_geo <- read_csv("Data/geo_dict_bk1850.csv")
```
```{r}
head(mn_geo)
```

# combined dictionary
```{r}
#full_mn_dict <- full_join(morse_mn, mn_geo, by = "ED")
#full_bk_dict <- full_join(morse_bk, bk_geo, by = "ED")
full_mn_dict <- mn_geo
full_bk_dict <- bk_geo
```


```{r}
head(full_mn_dict)
```


## MN
```{r}
full_mn_dict <- gather(data = full_mn_dict, key = item, 
                          value = value, St1:St164) %>% 
  select(-item) %>% group_by(Ward) %>% ungroup()
full_mn_dict <- na.omit(full_mn_dict)
colnames(full_mn_dict)[2] = "streets"
```
```{r}
full_mn_dict <- full_mn_dict %>%
  dplyr::arrange(streets) %>%
  melt(., id.vars = c("streets"), variable.name = "Ward") %>%
  select(-c(Ward)) %>%
  distinct(streets, value) %>%
  dplyr::group_by(value) %>%
  dplyr::mutate(rn = paste0("Street", 1:n())) %>%
  tidyr::spread(rn, streets)

colnames(full_mn_dict)[1]="Ward"
full_mn_dict <- full_mn_dict[mixedorder(colnames(full_mn_dict))]
```

```{r}
head(full_bk_dict)
```

## BK

```{r}
full_bk_dict <- gather(data = full_bk_dict, key = item, 
                          value = value, St1:St86) %>% 
  select(-item) %>% group_by(Ward) %>% ungroup()
full_bk_dict <- na.omit(full_bk_dict)
colnames(full_bk_dict)[2] = "streets"
```
```{r}
full_bk_dict <- full_bk_dict %>%
  dplyr::arrange(streets) %>%
  melt(., id.vars = c("streets"), variable.name = "Ward") %>%
  select(-c(Ward)) %>%
  distinct(streets, value) %>%
  dplyr::group_by(value) %>%
  dplyr::mutate(rn = paste0("Street", 1:n())) %>%
  tidyr::spread(rn, streets)

colnames(full_bk_dict)[1]="Ward"
full_bk_dict <- full_bk_dict[mixedorder(colnames(full_bk_dict))]
```

```{r}
write_csv(full_mn_dict, "Data/full_mn_dict1850.csv")
write_csv(full_bk_dict, "Data/full_bk_dict1850.csv")
```

