---
title: "Flags and house number range"
author: "Chang Xu"
output: html_notebook
---

```{r, include=FALSE}
knitr::opts_chunk$set(error = TRUE)
knitr::opts_chunk$set(cache = F)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
options(mc.cores = parallel::detectCores())
library(zoo)
library(magrittr)
library(dplyr)
library(tidyverse)
library(openxlsx)
library(readxl)
library(stringr)
library(fuzzyjoin)
library(tm)
library(english)
library(reshape2)
library(gtools)
library(compare)
library(purrr)
```

# load data
```{r}
mn <- read_csv("Data/combine_mn1850.csv")
bk <- read_csv("Data/combine_bk1850.csv")
```

# MN
```{r}
head(mn)
```


```{r}
mn$flag <- rep(NA, nrow(mn))
```

```{r}
head(mn)
```
## Missing house Number (incomplete)

```{r}
mn$flag[!complete.cases(mn[,c(6:9)])] <- "IN"
```

## Even odd 

```{r}
mn$flag[(mn$Left_Low %% 2 != mn$Left_High %% 2) == TRUE] <- "EO"
mn$flag[(mn$Right_Low %% 2 != mn$Right_High %% 2) == TRUE] <- "EO"
```

## wrong house number

```{r}
mn$flag[(abs(mn$Left_High - mn$Right_High) > 10) == TRUE] <- "WN"
mn$flag[(abs(mn$Left_Low - mn$Right_Low) > 10) == TRUE] <- "WN"
```

```{r}
write_csv(mn, "Data/mn_seg_flag1850.csv")
```

## House number range
```{r}
mn
```


```{r}
mnr <- mn %>% group_by(Ward, Name) %>% 
  summarise(Min = min(Left_Low, Right_Low), Max = max(Left_High, Right_High))
```
```{r}
mnr
```



```{r}
write_csv(mnr, "Data/mn_seg_add_range1850.csv")
```



# BK

```{r}
bk$flag <- rep(NA, nrow(bk))
```

```{r}
head(bk)
```

## Missing house Number (incomplete)

```{r}
bk$flag[!complete.cases(bk[,c(6:9)])] <- "IN"
```

## Even odd 

```{r}
bk$flag[(bk$Left_Low %% 2 != bk$Left_High %% 2) == TRUE] <- "EO"
bk$flag[(bk$Right_Low %% 2 != bk$Right_High %% 2) == TRUE] <- "EO"
```

## wrong house number

```{r}
bk$flag[(abs(bk$Left_High - bk$Right_High) > 10) == TRUE] <- "WN"
bk$flag[(abs(bk$Left_Low - bk$Right_Low) > 10) == TRUE] <- "WN"
```

```{r}
write_csv(bk, "Data/bk_seg_flag1850.csv")
```

## House number range

```{r}
bkr <- bk %>% group_by(Ward, Name) %>% 
  summarise(Min = min(Left_Low, Right_Low), Max = max(Left_High, Right_High))

bkr
```
```{r}
write_csv(bkr, "Data/bk_seg_add_range1850.csv")
```

















