---
title: "Combined Dict"
author: "Chang Xu"
output: html_notebook
---


```{r, include=FALSE}
knitr::opts_chunk$set(error = TRUE)
knitr::opts_chunk$set(cache = F)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
options(mc.cores = parallel::detectCores())
library(zoo)
library(magrittr)
library(dplyr)
library(tidyverse)
library(openxlsx)
library(readxl)
library(stringr)
library(fuzzyjoin)
library(tm)
library(english)
library(reshape2)
library(gtools)
library(compare)
library(purrr)
```

## load data

```{r}
morse_mn <- read_csv("Data/morse_mn1910.csv")
morse_bk <- read_csv("Data/morse_bk1910.csv")
```
```{r}
mn_seg <- read_csv("Data/mn_segments_1910export.csv")
bk_seg <- read_csv("Data/bk_segments_1910export.csv")
```

## rearrange Morse data
```{r}
## MN
colnames(morse_mn) <- gsub("M_St", "St", colnames(morse_mn))
test <- morse_mn
test1 = test %>%
  gather(colnames(test)[-1], key = "StreetNum", value = "StreetName") 
mn_ed <- na.omit(test1) %>% select(ED, Name = StreetName)
```
```{r}
## BK
colnames(morse_bk) <- gsub("M_St", "St", colnames(morse_bk))
test <- morse_bk
test1 = test %>%
  gather(colnames(test)[-1], key = "StreetNum", value = "StreetName") 
bk_ed <- na.omit(test1) %>% select(ED, Name = StreetName)
```

## clean segment data
```{r}
# clean function
clean_streets<-function(x){
  x<-gsub("\\<SRT\\>$|\\<SR\\>$\\<SRT\\>$|\\<STR\\>$|\\<SST\\>$|\\<SEET\\>$|\\<TREET\\>$|\\<SHEER\\>$|\\<SHEE\\>$|\\<STREE\\>$|\\<SREET\\>$|\\<REET\\>$|\\<STEE\\>$|\\<ST\\>$","STREET",x)
  x<-gsub("\\<N\\>","NORTH",x)
  x<-gsub("\\<S\\>","SOUTH",x)
  x<-gsub("\\<E\\>","EAST",x)
  x<-gsub("\\<W\\>","WEST",x)
  x<-gsub("\\<DR\\>|\\<DV\\>|\\<DE\\>$|\\<DRV\\>|\\<DRI\\>|\\<DRIV\\>|\\<DRIE\\>","DRIVE",x) 
  x<-gsub("\\<CIR\\>|\\<CRL\\>|\\<CIRC\\>|\\<CR\\>|\\<CL\\>|\\<CIRCL\\>|\\<CICLE\\>","CIRCLE",x)
  x<-gsub("\\<AVE\\>|\\<AV\\>|\\<AVN\\>|\\<AVEN\\>|\\<AVENU\\>","AVENUE",x)
  x<-gsub("\\<CT\\>|\\<CRT\\>|\\<CTR\\>|\\<COUR\\>|\\<COT\\>|\\<CORT\\>","COURT",x)
  x<-gsub("\\<BLVD\\>|\\<BVLD\\>|\\<BV\\>|\\<BLD\\>|\\<BD\\>|\\<BL\\>|\\<BLV\\>","BOULEVARD",x)
  x<-gsub("\\<RD\\>|\\<RAD\\>|\\<ROD\\>","ROAD",x)
  x<-gsub("\\<ALY\\>|\\<AL\\>|\\<ALLY\\>|\\<ALEY\\>|\\<ALLE\\>|\\<AY\\>","ALLEY",x)
  x<-gsub("\\<PL\\>|\\<PLC\\>|\\<PLE\\>|\\<PC\\>|\\<PLAC\\>|\\<PLCE\\>|\\<PCE\\>","PLACE",x)
  x<-gsub("\\<PK\\>|\\<PRK\\>|\\<PRAK\\>|\\<PAK\\>","PARK",x)
  x<-gsub("\\<PKWY\\>|\\<PARKW\\>|\\<PWY\\>|\\<PKW\\>|\\<PRKWY\\>|\\<PKWY\\>|\\<PKW\\>","PARKWAY",x)
  x<-gsub("\\<APPR\\>|\\<APR\\>|\\<APPROA\\>|\\<APRCH\\>|\\<APPRCH\\>","APPROACH",x)
  x<-gsub("\\<TER\\>|\\<TERR\\>|\\<TRC\\>|\\<TRCE\\>|\\<TR\\>","TERRACE",x)
  x<-gsub("\\<PLZ\\>|\\<PLAZ\\>|\\<PZ\\>|\\<PLZA\\>","PLAZA",x)
  x<-gsub("\\<LN\\>|\\<LNE\\>|\\<LAN\\>","LANE",x)
  x<-gsub("\\<BRG\\>|\\<BRGD\\>|\\<BGE\\>","BRIDGE",x)
  x<-gsub("\\<HL\\>|\\<HLL\\>|\\<HIL\\>","HILL",x)
  x<-gsub("\\<HTS\\>|\\<HT\\>|\\<HEIGHT\\>|\\<HEGHTS\\>|\\<HHT\\>|\\<HEIGT\\>","HEIGHTS",x) 
  x<-gsub(".*\\((.*)\\).*", "\\1", x)
  x<-str_remove(x,"STREET")
  x<-gsub("\\d+\\ - *\\d*|\\d+\\ TO *\\d*|\\d+\\-\\d*","",x) #remove addresses
  

  ## dealing with numbered streets
x<-gsub("(\\d)(ST|ND|RD|TH)\\b", "\\1", x)
x<-str_remove(x, "(?<=[0-9])(ST|ND|RD|TH)")
x<-gsub("\\<ONE HUNDRED\\>|\\<ONEHUNDRED\\>|\\<HUNDRED\\>|\\<HUDRED\\>|\\<HUNDED\\>","1",x) 
x<-gsub("\\<TWO HUNDRED\\>|\\<TWOHUNDRED\\>","2",x)
x<-gsub("-"," ",x)
x<-gsub("\\<AND\\>"," ",x)
x<-gsub("&"," ",x)
x<-gsub("\\<1ST\\>|\\b1\\b","FIRST",x)
x<-gsub("\\<2ND\\>|\\b2\\b","SECOND",x)
x<-gsub("\\<3RD\\>|\\b3\\b","THIRD",x)
x<-gsub("\\<4TH\\>|\\b4\\b","FOURTH",x)
x<-gsub("\\<5TH\\>|\\b5\\b","FIFTH",x)
x<-gsub("\\<6TH\\>|\\b6\\b","SIXTH",x)
x<-gsub("\\<7TH\\>|\\b7\\b","SEVENTH",x)
x<-gsub("\\<8TH\\>|\\b8\\b","EIGHTH",x)
x<-gsub("\\<9TH\\>|\\b9\\b","NINTH",x)
x<-gsub("\\<10TH\\>|\\b10\\b","TENTH",x)
x<-gsub("\\<11TH\\>|\\b11\\b","ELEVENTH",x)
x<-gsub("\\<12TH\\>|\\b12\\b","TWELFTH",x)
x<-gsub("\\<13TH\\>|\\b13\\b","THIRTEENTH",x)
x<-gsub("\\<14TH\\>|\\b14\\b","FORTEENTH",x)
x<-gsub("\\<15TH\\>|\\b15\\b","FIFTEENTH",x)
x<-gsub("\\<16TH\\>|\\b16\\b","SIXTEENTH",x)
x<-gsub("\\<17TH\\>|\\b17\\b","SEVENTEENTH",x)
x<-gsub("\\<18TH\\>|\\b18\\b","EIGHTEENTH",x)
x<-gsub("\\<19TH\\>|\\b19\\b","NINETEENTH",x)


x<-gsub("\\<TWENTY\\>|\\<TWENTI\\>|\\<TENTI\\>","2",x)
x<-gsub("\\<THIRTY\\>|\\<THIRTHY\\>|\\<THIRTEY\\>|\\<TIRTY\\>|\\<TRITHY\\>","3",x)
x<-gsub("\\<FORTY\\>|\\<FOURTY\\>|\\<FOURTHY\\>|\\<FRTY\\>","4",x)
x<-gsub("\\<FIFTY\\>|\\<FIFTEY\\>|\\<FIFT\\>|\\<FITY\\>|\\<FIFTHY\\>","5",x)
x<-gsub("\\<SIXTY\\>|\\<SXTY\\>|\\<SIXY\\>|\\<SXTY\\>|\\<SIXTHY\\>|\\<SIXTEY\\>","6",x)
x<-gsub("\\<SEVENT\\>|\\<SEVENTY\\>|\\<SEVENTEY\\>|\\<SVENTY\\>|\\<SEVENTI\\>","7",x)
x<-gsub("\\<EIGHTY\\>|\\<EIGHTEY\\>|\\<EIGHTE\\>","8",x)
x<-gsub("\\<UNITY\\>|\\<NINTH\\>|\\<NINETY\\>|\\<NINETEY\\>|\\<NINETIETH\\>|\\<NINTY\\>","9",x)
x<-gsub("\\<FRIST\\>|\\<FIST\\>|\\<FRST\\>|\\<FIRST\\>|\\<ONE\\>","1",x)
x<-gsub("\\<SECOND\\>|\\<SECORD\\>|\\<SCOND\\>|\\<SECOND\\>|\\<TWO\\>","2",x)
x<-gsub("\\<THRID\\>|\\<THIRD\\>|\\<TIRD\\>|\\<TRIHD\\>|\\<THREE\\>","3",x)
x<-gsub("\\<FORTH\\>|\\<FOURTH\\>|\\<FROTH\\>|\\<FROUTH\\>|\\<FOUR\\>","4",x)
x<-gsub("\\<FIFETH\\>|\\<FIFTH\\>|\\<FIFFTH\\>|\\<FIFTHE\\>|\\<FIVE\\>","5",x)
x<-gsub("\\<SIXTH\\>|\\<SXTH\\>|\\<SITH\\>|\\<SIHXT\\>|\\<SIX\\>","6",x)
x<-gsub("\\<SEVENTH\\>|\\<SVEN\\>|\\<SVENTH\\>|\\<SEVENH\\>|\\<SEVENT\\>|\\<SEVEN\\>","7",x)
x<-gsub("\\<EIGHTH\\>|\\<EIGHTEH\\>|\\<EITH\\>|\\<EIGHT\\>","8",x)
x<-gsub("\\<NINETH\\>|\\<NINTH\\>|\\<NINT\\>|\\<NINETH\\>|\\<NINE\\>|\\<NIN\\>","9",x)
x<-gsub("\\<TWENTIETH\\>|\\<TWENTIEFTH\\>","20",x) #NEW
x<-gsub("\\<THIRTIETH\\>|\\<THIRTIEFTH\\>","30",x)
x<-gsub("\\<FORTIETH\\>|\\<FOURTIETH\\>","40",x)
x<-gsub("\\<FIFTIETH\\>","50",x)
x<-gsub("\\<SIXTIETH\\>","60",x)
x<-gsub("\\<SEVENTIETH\\>","70",x)
x<-gsub("\\<EIGHTIETH\\>","80",x)
x<-gsub("\\<NINETIETH\\>|\\<NINTIETH\\>","90",x)
x<-gsub("(?<=\\d) (?=\\d)","",x,perl = T) #new close gaps between all numbers
## place names
  ##x<-gsub("\\bSTR\\b","", x)
  x<-gsub("^\\bST\\b","SAINT", x) 
  x<-gsub("\\bHOUSE\\b","", x)
  x<-gsub("\\bHOSTEL\\b","", x)
  x<-gsub("\\bHOTEL\\b","", x)
  x<-gsub("\\bLODGE\\b","", x)
  x<-gsub("\\bLODGING\\b","", x)
  x<-trimws(x, "both")
  x<-gsub("\\<N\\>","NORTH",x)
  ##x<-gsub("\\<ST\\>","",x)
  ##x<-gsub("\\<STREET\\>","",x)
} 
```

```{r}
mn_seg$MN_STREET1910_FULL_STREE = clean_streets(mn_seg$MN_STREET1910_FULL_STREE)
mn_seg$MN_STREET1910_Y1910NAMEALT = clean_streets(mn_seg$MN_STREET1910_Y1910NAMEALT)
mn_seg$MN_STREET1910_Y1910NAMESTREET = clean_streets(mn_seg$MN_STREET1910_Y1910NAMESTREET)

bk_seg$BK_STREET1910_FULL_STREE = clean_streets(bk_seg$BK_STREET1910_FULL_STREE)
bk_seg$BK_STREET1910_Y1910NAMEALT = clean_streets(bk_seg$BK_STREET1910_Y1910NAMEALT)
bk_seg$BK_STREET1910_Y1910NAMESTREET = clean_streets(bk_seg$BK_STREET1910_Y1910NAMESTREET)
```

```{r}
mn_seg <- mn_seg %>% select(-XCoord, -YCoord)
bk_seg <- bk_seg %>% select(-XCoord, -YCoord)
```
```{r}
mn_seg <- as_tibble(sapply(mn_seg, toupper))
bk_seg <- as_tibble(sapply(bk_seg, toupper))
```

# arrange seg data
```{r}
colnames(mn_seg) <- c("ObjectID", "Full_Name", "Name1910", 
                      "Left_Low", "Left_High", "Right_Low", "Right_High",
                      "JoinId", "AltName", "ED_Minus", "ED_Plus")
mn_seg <- mn_seg[c(2, 3, 9, 4, 5, 6, 7, 10, 11, 1, 8)]

mn_seg$Left_Low <- as.numeric(mn_seg$Left_Low)
mn_seg$Left_High <- as.numeric(mn_seg$Left_High)
mn_seg$Right_Low <- as.numeric(mn_seg$Right_Low)
mn_seg$Right_High <- as.numeric(mn_seg$Right_High)
mn_seg$ED_Minus <- as.numeric(mn_seg$ED_Minus)
mn_seg$ED_Plus <- as.numeric(mn_seg$ED_Plus)
```

```{r}
colnames(bk_seg) <- c("ObjectID", "Full_Name", "Name1910", 
                      "Left_Low", "Left_High", "Right_Low", "Right_High",
                      "JoinId", "AltName", "ED_Minus", "ED_Plus")
bk_seg <- bk_seg[c(2, 3, 9, 4, 5, 6, 7, 10, 11, 1, 8)]

bk_seg$Left_Low <- as.numeric(bk_seg$Left_Low)
bk_seg$Left_High <- as.numeric(bk_seg$Left_High)
bk_seg$Right_Low <- as.numeric(bk_seg$Right_Low)
bk_seg$Right_High <- as.numeric(bk_seg$Right_High)
bk_seg$ED_Minus <- as.numeric(bk_seg$ED_Minus)
bk_seg$ED_Plus <- as.numeric(bk_seg$ED_Plus)
```


## create Name column with priority
```{r}
mn_seg$Name <- NA
for (i in nrow(mn_seg)) {
  if (mn_seg$Name1910 != "NULL") {
    mn_seg$Name <- mn_seg$Name1910
  } else if (mn_seg$Full_Name != "NULL") {
    mn_seg$Name <- mn_seg$Full_Name
  } else {
    mn_seg$Name <- mn_seg$AltName
  }
}
```
```{r}
bk_seg$Name <- NA
for (i in nrow(bk_seg)) {
  if (bk_seg$Name1910 != "NULL") {
    bk_seg$Name <- bk_seg$Name1910
  } else if (bk_seg$Full_Name != "NULL") {
    bk_seg$Name <- bk_seg$Full_Name
  } else {
    bk_seg$Name <- bk_seg$AltName
  }
}
```


## spread sheet

```{r}
mn_seg1 <- mn_seg %>% filter(ED_Minus == ED_Plus) %>% 
  mutate(ED = ED_Minus) %>% select(-ED_Minus, -ED_Plus)
```
```{r}
mn_seg2 <- mn_seg %>% filter(ED_Minus != ED_Plus) %>% 
  rename(ED = ED_Minus) %>% select(-ED_Plus)
```
```{r}
mn_seg3 <- mn_seg %>% filter(ED_Minus != ED_Plus) %>% 
  rename(ED = ED_Plus) %>% select(-ED_Minus)
```

```{r}
mn_seg4 <- rbind(mn_seg1, mn_seg2, mn_seg3)
mn_seg4 <- mn_seg4[c(11, 10, 1:9)]
```



```{r}
bk_seg1 <- bk_seg %>% filter(ED_Minus == ED_Plus) %>% 
  mutate(ED = ED_Minus) %>% select(-ED_Minus, -ED_Plus)
```
```{r}
bk_seg2 <- bk_seg %>% filter(ED_Minus != ED_Plus) %>% 
  rename(ED = ED_Minus) %>% select(-ED_Plus)
```
```{r}
bk_seg3 <- bk_seg %>% filter(ED_Minus != ED_Plus) %>% 
  rename(ED = ED_Plus) %>% select(-ED_Minus)
```

```{r}
bk_seg4 <- rbind(bk_seg1, bk_seg2, bk_seg3)
bk_seg4 <- bk_seg4[c(11, 10, 1:9)]
```

## combine with Morse
```{r}
combine_mn <- full_join(mn_ed, mn_seg4, by = c("ED", "Name"))
combine_bk <- full_join(bk_ed, bk_seg4, by = c("ED", "Name"))
```
```{r}
## write_csv(combine_mn, "Data/combine_mn.csv")
## write_csv(combine_bk, "Data/combine_bk.csv")
```






