---
title: "Nested Data"
author: "Chang Xu"
output: html_notebook
---

```{r, include=FALSE}
knitr::opts_chunk$set(error = TRUE)
knitr::opts_chunk$set(cache = F)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
options(mc.cores = parallel::detectCores())
library(zoo)
library(magrittr)
library(dplyr)
library(tidyverse)
library(openxlsx)
library(readxl)
library(stringr)
library(fuzzyjoin)
library(tm)
library(english)
library(reshape2)
library(gtools)
library(compare)
library(purrr)
```

# load data & clean data

```{r}
mn <- read_csv("Data/combine_mn.csv")
bk <- read_csv("Data/combine_bk.csv")
```


## nest data

### nest by ED 
```{r}
mn_nest <- mn %>% group_by(ED) %>% nest()
```

**note:** right high, 30.0 - 39.0, 37.5?

* check overall street range within ED

* apply alt names to suitable streets within ED

* Export to interactive format

```{r}
bk_nest <- bk %>% group_by(ED) %>% nest()
```


```{r}
## saveRDS(mn_nest, "Data/mn_nest.rds")
## saveRDS(bk_nest, "Data/bk_nest.rds")
```

```{r}
mn_nest <- readRDS("Data/mn_nest.rds")
```

```{r}
fx <- function(set) {
  group_by(set, Name)
}
mn_nest1 <- mn_nest %>% transmute(ED, Data = map(data, fx))
```





