---
title: "clean segment & geo_dict"
author: "Chang Xu"
output: html_notebook
---

```{r, include=FALSE}
knitr::opts_chunk$set(error = TRUE)
knitr::opts_chunk$set(cache = F)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
options(mc.cores = parallel::detectCores())
library(zoo)
library(magrittr)
library(dplyr)
library(tidyverse)
library(openxlsx)
library(readxl)
library(stringr)
library(fuzzyjoin)
library(tm)
library(english)
library(reshape2)
library(gtools)
library(compare)
library(purrr)
```

# load data & clean data

```{r}
mn_seg <- read_csv("Data/mn_segments_1880export.csv")
bk_seg <- read_csv("Data/bk_segments_1880export.csv")
```

```{r}
source("lib/clean_function.R")
```

```{r}
mn_seg$MN_STREET1880_FULL_STREE = clean(mn_seg$MN_STREET1880_FULL_STREE)
mn_seg$MN_STREET1880_Y1880NAMEALT = clean(mn_seg$MN_STREET1880_Y1880NAMEALT)
mn_seg$MN_STREET1880_Y1880NAMESTREET = clean(mn_seg$MN_STREET1880_Y1880NAMESTREET)

bk_seg$BK_STREET1880_FULL_STREE = clean(bk_seg$BK_STREET1880_FULL_STREE)
bk_seg$BK_STREET1880_Y1880NAMEALT = clean(bk_seg$BK_STREET1880_Y1880NAMEALT)
bk_seg$BK_STREET1880_Y1880NAMESTREET = clean(bk_seg$BK_STREET1880_Y1880NAMESTREET)
```

## re-arrange dataset
```{r}
#mn_seg <- mn_seg %>% select(-XCoord, -YCoord)
#bk_seg <- bk_seg %>% select(-XCoord, -YCoord)
```

```{r}
mn_seg <- as_tibble(sapply(mn_seg, toupper))
bk_seg <- as_tibble(sapply(bk_seg, toupper))
```

```{r}
colnames(mn_seg) <- c("ObjectID", "Full_Name", "Name1880", 
                      "Left_Low", "Left_High", "Right_Low", "Right_High",
                      "JoinId", "AltName", "ED_Minus", "ED_Plus")
mn_seg <- mn_seg[c(2, 3, 9, 4, 5, 6, 7, 10, 11, 1, 8)]

mn_seg$Left_Low <- as.numeric(mn_seg$Left_Low)
mn_seg$Left_High <- as.numeric(mn_seg$Left_High)
mn_seg$Right_Low <- as.numeric(mn_seg$Right_Low)
mn_seg$Right_High <- as.numeric(mn_seg$Right_High)
mn_seg$ED_Minus <- as.numeric(mn_seg$ED_Minus)
mn_seg$ED_Plus <- as.numeric(mn_seg$ED_Plus)
```

```{r}
colnames(bk_seg) <- c("ObjectID", "Full_Name", "Name1880", 
                      "Left_Low", "Left_High", "Right_Low", "Right_High",
                      "JoinId", "AltName", "ED_Minus", "ED_Plus")
bk_seg <- bk_seg[c(2, 3, 9, 4, 5, 6, 7, 10, 11, 1, 8)]

bk_seg$Left_Low <- as.numeric(bk_seg$Left_Low)
bk_seg$Left_High <- as.numeric(bk_seg$Left_High)
bk_seg$Right_Low <- as.numeric(bk_seg$Right_Low)
bk_seg$Right_High <- as.numeric(bk_seg$Right_High)
bk_seg$ED_Minus <- as.numeric(bk_seg$ED_Minus)
bk_seg$ED_Plus <- as.numeric(bk_seg$ED_Plus)
```

## create Name column with priority
```{r}
mn_seg <- mn_seg %>% rowwise() %>% 
  mutate(Name = ifelse(Name1880 != "NULL", Name1880, 
                          ifelse(Full_Name != "NULL", Full_Name, AltName))) %>%
  ungroup()
```

```{r}
bk_seg <- bk_seg %>% rowwise() %>% 
  mutate(Name = ifelse(Name1880 != "NULL", Name1880, 
                          ifelse(Full_Name != "NULL", Full_Name, AltName))) %>%
  ungroup()
```

# cleaned seg data
```{r}
mn_seg <- mn_seg[c(12, 1:11)]
```
```{r}
bk_seg <- bk_seg[c(12, 1:11)]
```

```{r}
write_csv(mn_seg, "Data/segment_mn.csv")
write_csv(bk_seg, "Data/segment_bk.csv")
```

## create geo_dict

```{r}
mn_seg_list1 <- mn_seg %>% filter(ED_Minus == ED_Plus) %>%
  mutate(ED = ED_Minus) %>% select(ED, Name, ObjectID, JoinId)
```
```{r}
mn_seg_list2 <- mn_seg %>% filter(ED_Minus != ED_Plus) %>% 
  select(Name, ED_Minus, ObjectID, JoinId) %>% rename(ED = ED_Minus)
mn_seg_list2 <- mn_seg_list2[c(2, 1, 3, 4)]
```
```{r}
mn_seg_list3 <- mn_seg %>% filter(ED_Minus != ED_Plus) %>% 
  select(Name, ED_Plus, ObjectID, JoinId) %>% rename(ED = ED_Plus)
mn_seg_list3 <- mn_seg_list3[c(2, 1, 3, 4)]
```
```{r}
mn_seg_list4 <- rbind(mn_seg_list1, mn_seg_list2, mn_seg_list3)
```

```{r}
mn_seg_list5 <- mn_seg_list4 %>% 
  spread(key = ED, value = Name, fill = NA) %>% select(-ObjectID, -JoinId)
colnames(mn_seg_list5) <- sub("", "ED", colnames(mn_seg_list5))
mn_seg_list5 <- as.data.frame(mn_seg_list5)
```
```{r}
mn_seg_list6 <- apply(mn_seg_list5, 2, sort)
```
```{r}
mn_seg_list7 <- lapply(mn_seg_list6, unique)
```

```{r}
maxlen <- max(lengths(mn_seg_list7))
B <- lapply(mn_seg_list7, function(lst) c(lst, rep(NA, maxlen - length(lst))))
names(B) <- paste(colnames(mn_seg_list5))
C <- lapply(B, unlist)
my <- as.data.frame(C)
```

```{r}
geo_dict<- t(my)
rownames(geo_dict) <- c(1:nrow(geo_dict))
colnames(geo_dict) <- paste0("St", 1:ncol(geo_dict))
```
```{r}
ED <- colnames(my) 
ED <- sub("ED", "", ED)
ED <- as.numeric(ED)
```
```{r}
geo_dict_mn <- as_tibble(cbind(ED, geo_dict))
geo_dict_mn$ED <- as.numeric(geo_dict_mn$ED)
```


```{r}
write_csv(geo_dict_mn, "Data/geo_dict_mn.csv")
```

```{r}
bk_seg_list1 <- bk_seg %>% filter(ED_Minus == ED_Plus) %>%
  mutate(ED = ED_Minus) %>% select(ED, Name, ObjectID, JoinId)
```
```{r}
bk_seg_list2 <- bk_seg %>% filter(ED_Minus != ED_Plus) %>% 
  select(Name, ED_Minus, ObjectID, JoinId) %>% rename(ED = ED_Minus)
bk_seg_list2 <- bk_seg_list2[c(2, 1, 3, 4)]
```
```{r}
bk_seg_list3 <- bk_seg %>% filter(ED_Minus != ED_Plus) %>% 
  select(Name, ED_Plus, ObjectID, JoinId) %>% rename(ED = ED_Plus)
bk_seg_list3 <- bk_seg_list3[c(2, 1, 3, 4)]
```
```{r}
bk_seg_list4 <- rbind(bk_seg_list1, bk_seg_list2, bk_seg_list3)
```

```{r}
bk_seg_list5 <- bk_seg_list4 %>% 
  spread(key = ED, value = Name, fill = NA) %>% select(-ObjectID, -JoinId)
colnames(bk_seg_list5) <- sub("", "ED", colnames(bk_seg_list5))
bk_seg_list5 <- as.data.frame(bk_seg_list5)
```

```{r}
bk_seg_list6 <- apply(bk_seg_list5, 2, sort)
```
```{r}
bk_seg_list7 <- lapply(bk_seg_list6, unique)
```

```{r}
maxlen <- max(lengths(bk_seg_list7))
B <- lapply(bk_seg_list7, function(lst) c(lst, rep(NA, maxlen - length(lst))))
names(B) <- paste(colnames(bk_seg_list5))
C <- lapply(B, unlist)
my <- as.data.frame(C)
```

```{r}
geo_dict<- t(my)
rownames(geo_dict) <- c(1:nrow(geo_dict))
colnames(geo_dict) <- paste0("St", 1:ncol(geo_dict))
```
```{r}
ED <- colnames(my) 
ED <- sub("ED", "", ED)
ED <- as.numeric(ED)
```
```{r}
geo_dict_bk <- as_tibble(cbind(ED, geo_dict))
geo_dict_bk$ED <- as.numeric(geo_dict_bk$ED)
```

```{r}
write_csv(geo_dict_bk, "Data/geo_dict_bk.csv")
```














